### ISSUE TITLE
libsqsh tips

### ISSUE THREAD

**Issue by Gottox** [probonopd/Filer#1]
https://github.com/probonopd/Filer/blob/d254dadbc8495783b6a6b080c804e4e3b4fc7a13/src/SqshReader.cpp#L69-L74
You can actually use [`sqsh_directory_iterator_name_dup(iterator)`](https://github.com/Gottox/libsqsh/blob/03100190d8ab0c157e31575bb3cbacc8d8c744c1/include/sqsh_directory.h#L159-L171) to get a zero terminated string. It actually does exactly the same as you're doing manually here.

**Comment by probonopd** [comment]
Thanks for your careful review. I have adopted your suggested improvement.
