### ISSUE TITLE
Duplicate menu bug

### ISSUE THREAD

**Issue by louies0623** [probonopd/Filer#13]
![20230928_212639](https://github.com/probonopd/Filer/assets/44593430/4cfa7c73-4420-4cb0-ab67-06f9166eec42)
After opening some windows and then pressing Filer.app to open a new window, this bug will appear.

**Comment by probonopd** [comment]
If you are double-clicking Filler.app, then you should get:

> Another file manager is already running.
Please quit it first.

Only one Filer must run at any time.

**Comment by probonopd** [comment]
When this problem happens, please run `ps ax | grep Filer`. Thanks!

**Comment by louies0623** [comment]
![20230929_172131](https://github.com/probonopd/Filer/assets/44593430/e5bfcbf9-0851-4ad8-ad26-a8e64080d36c)

**Comment by probonopd** [comment]
Looks Good. 

Strange bug. I need to reproduce this. Does it also happen with other apps? Is this on a very slow machine?

**Comment by louies0623** [comment]
Yes it does, the machine is not slow.

**Comment by louies0623** [comment]
Update: This also happens in other software e.g Falkon , so please migrate this issue.

**Comment by probonopd** [comment]
I cannot move from https://github.com/probonopd/... to https://github.com/helloSystem/...
